### ISSUE TITLE
ignoring checks requires exact match on filename, documentation in staticcheck is incorrect

### ISSUE THREAD

**Issue by tamird** [dominikh/go-lint#2]
From https://godoc.org/path/filepath#Match:
> Match requires pattern to match all of name, not just a substring.

This function is used here: https://github.com/dominikh/go-lint/commit/3a0742e3d7107e76a7759a780ee796fa0f79d220

Therefore, it seems that the documentation in https://github.com/dominikh/go-staticcheck#ignoring-checks is incorrect, since the ignore strings listed will not actually match.

I'm filing this issue here because this is the repo in which the fix would be implemented. I would suggest that the ignore-check syntax be more permissive, to allow partial matches.

@dominikh 

By the way, this project, as well as go-simple and go-staticcheck are **outstanding** and we use them quite heavily in CockroachDB. Thanks so much for your work!

**Comment by dominikh** [comment]
You're correct that Match requires the whole pattern to match. When running the tools on packages (for example `staticcheck honnef.co/go/lint`, we will path the following kind of name to Match: `honnef.co/go/lint/lint.go`, which a pattern like `honnef.co/go/lint/*.go` would match.

If you run staticcheck on single files, you will need to provide the entire path as there will be no import path. But this mode of running is discouraged in general, as you will either need to provide all files of a package, or end up with an adhoc package that doesn't type check because it's missing identifiers.

One that that currently doesn't work quite as expected is a pattern like `*/*_test.go` as it will fail to match most packages due to Go's lack of a recursive glob operator. We might have to revisit that.

Based on that I believe that the examples in the README work as they should. If you're still facing problems, please provide an example invocation of the tool, expected and actual output.

> By the way, this project, as well as go-simple and go-staticcheck are outstanding and we use them quite heavily in CockroachDB. Thanks so much for your work!

Thanks! It makes me really happy to hear that.

**Comment by tamird** [comment]
To my surprise, using the full package path worked! Thank you for the prompt response!
